[platformio]
default_envs = esp8266

[env]
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
  -D USE_MQTT
lib_deps =
  EspConnectivity = symlink://../..

[env:esp8266]
platform = espressif8266
board = d1_mini

[env:esp32]
platform = espressif32
board = esp32dev
